import type { Product, Stat } from "@/types";

export const PRODUCTS: Product[] = [
  {
    id: "dior-sauvage",
    brand: "Dior",
    name: "Sauvage",
    description:
      "Las Notas de Salida son bergamota, mandarina y elemí; la Nota de Corazón es sándalo; las Notas de Fondo son incienso de olíbano (franquincienso), haba tonka y vainilla.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/sauvage.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 3,
    badge: "new",
  },
  {
    id: "chanel-bleu",
    brand: "Chanel",
    name: "Bleu",
    description:
      "Las Notas de Salida son Ralladura de limón, bergamota, menta y abrótano; las Notas de Corazón son lavanda, piña, geranio y notas verdes; las Notas de Fondo son sándalo, cedro, Amberwood, Iso E Super y haba tonka.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/chanel-bleu.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 1,
    badge: "low",
  },
  {
    id: "acqua-profondo",
    brand: "Acqua Di Gio Profondo",
    name: "Profondo",
    description:
      " Las Notas de Salida son notas marinas, Aquozone, bergamota y mandarina verde; las Notas de Corazón son romero, lavanda, ciprés y resina almáciga del lentisco; las Notas de Fondo son Notas minerales, almizcle, pachulí y ámbar.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/profondo.png",
    categories: ["hombre"],
    stockStatus: "out-of-stock",
    stockCount: 3,
    badge: "out",
  },
  {
    id: "black-opium-yves-saint-laurent",
    brand: "Yves Saint Laurent",
    name: "Black Opium",
    description:
      "Notas de salida son pera, pimienta rosa y flor de azahar del naranjo. Notas de corazón son café, jazmín y almendra amarga. Notas de fondo son vainilla, pachulí y cedro.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/black-opium.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 6,
  },
  {
    id: "ralph-lauren-ralph",
    brand: "Ralph Lauren",
    name: "Ralph Lauren Ralph",
    description:
      "Hojas de manzano,mandarina italiana,osmanto japonés. Fresia amarilla,magnolia y boronia parda. Notas de Fondo son almizcle e iris blanco.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/ralph-ralp.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 6,
  },
  {
    id: "212-sexy-carolina-herrera",
    brand: "Carolina Herrera",
    name: "212 Sexy",
    description:
      "Las Notas de Salida son pimienta rosa, mandarina y bergamota; las Notas de Corazón son algodón de azúcar, gardenia, flores, pelargonio y rosa; las Notas de Fondo son vainilla, almizcle, sándalo, caramelo, pachulí y violeta.2",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/212-sexy.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 5,
  },
  {
    id: "tommy-hilfiger-impact",
    brand: "Tommy Hilfiger",
    name: "Impact",
    description:
      "La Nota de Salida es elemí; la Nota de Corazón es madera de oud; las Notas de Fondo son gamuza y vainilla.im",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/impact.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 4,
    badge: "new",
  },
  {
    id: "valentino-born-in-roma",
    brand: "Valentino",
    name: "Born in Roma",
    description:
      "La Nota de Salida es vainilla; la Nota de Corazón es lavanda; la Nota de Fondo es vetiver.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/born-in-roma.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "one-million-paco-rabanne",
    brand: "Paco Rabanne",
    name: "One Million",
    description:
      "La fragrancia contiene nardos, notas solares, sal, aceite de Monoi, ámbar gris, cuero, cachemira, ládano y pino.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/one-million.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "armani-code-giorgio-armani",
    brand: "Giorgio Armani",
    name: "Armani Code",
    description:
      "Las Notas de Salida son bergamota y hojas del bergamoto; las Notas de Corazón son iris, aldehídos, esclarea y raíz de lirio; las Notas de Fondo son haba tonka y cedro.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/armani-code.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "bad-boy-carolina-herrera",
    brand: "Carolina Herrera",
    name: "Bad Boy",
    description:
      "Las Notas de Salida son pimienta blanca, bergamota y pimienta rosa; las Notas de Corazón son cedro y esclarea; las Notas de Fondo son haba tonka y cacao.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/bad-boy.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "bharara-king",
    brand: "Bharara",
    name: "King",
    description:
      "Las Notas de Salida son naranja, bergamota y limón (lima ácida); la Nota de Corazón es notas afrutadas; las Notas de Fondo son vainilla, almizcle blanco y ámbar.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/king.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "angel-mugler-thierry-mugler",
    brand: "Thierry Mugler",
    name: "Angel Mugler",
    description:
      "Las Notas de Salida son algodón de azúcar, coco, casis (grosellero negro), melón, jazmín, bergamota, piña y mandarina; las Notas de Corazón son miel, bayas rojas, zarzamora (frambuesa negra), ciruela, chabacano, jazmín, durazno (melocotón), nuez moscada, alcaravea, orquídea, rosa y lirio de los valles (muguete); las Notas de Fondo son pachulí, chocolate, caramelo, vainilla, haba tonka, ámbar, almizcle y sándalo. ",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/angel-mugler.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "janeiro-pink-68",
    brand: "Sol Janeiro",
    name: "Sol Janeiro Pink 68",
    description:
      'En Brasil, un secreto de belleza esencial es ser "cheirosa" (sheh-ro-zah), lo que significa oler siempre delicioso. Vibrante e inesperado, este aroma afrutado-floral ofrece una tentación transportiva a través de los abundantes jardines soleados de Río. Este aroma inmersivo se besa de alegría y siempre es acogedor.',
    price: "$6.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/sol-janeiro-pink-68.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "acqua-di-gio-tradition",
    brand: "Giorgio Armani",
    name: "Acqua Di Gio Tradition",
    description:
      "Define la masculinidad con una mezcla de notas marinas, cítricas (bergamota, limón) y un fondo amaderado suave.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/acqua-di-gio-tradition.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "le-male-jpg",
    brand: "Jean Paul Gaultier",
    name: "Le Male",
    description:
      "Una fragancia que evoca la elegancia y sofisticación del hombre moderno, con notas de salida frescas y un fondo amaderado.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/le-male.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "black-xs-paco-rabanne",
    brand: "Paco Rabanne",
    name: "Black XS",
    description:
      "Una fragancia que combina notas de frutas frescas con un fondo amaderado y especiado.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/black-xs-paco-rabanne.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "lacoste-pure",
    brand: "Lacoste",
    name: "Lacoste Pure",
    description:
      "Una fragancia fresca y energizante que combina notas cítricas con un fondo amaderado.",
    price: "$6.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/lacoste-pure.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "212-vip-carolina-herrera",
    brand: "Carolina Herrera",
    name: "212 VIP",
    description:
      "Una fragancia que captura la esencia de la vida nocturna de Nueva York, con notas de ron, maracuyá y vainilla.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/212-vip-carolina-herrera.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "azzaro-most-wanted",
    brand: "Azzaro",
    name: "Most Wanted",
    description:
      "Fragancia intensa y adictiva que destaca por su carácter dulce y especiado con un fondo profundo y masculino",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/azzaro-most-wanted.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
];

const stockCount = PRODUCTS.reduce(
  (total, product) => total + product.stockCount,
  0,
);

export const STATS: Stat[] = [
  { value: `${PRODUCTS.length}`, label: "Fragancias" },
  { value: "14", label: "Marcas" },
  { value: `${stockCount}`, label: "En stock hoy" },
  { value: "24h", label: "Despacho" },
];
