import type { Product, Stat } from "@/types";

export const PRODUCTS: Product[] = [
  {
    id: "dior-sauvage",
    brand: "Dior",
    name: "Sauvage",
    description:
      "Las Notas de Salida son bergamota, mandarina y elemí; la Nota de Corazón es sándalo; las Notas de Fondo son incienso de olíbano (franquincienso), haba tonka y vainilla.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/sauvage.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 3,
  },
  {
    id: "chanel-bleu",
    brand: "Chanel",
    name: "Bleu",
    description:
      "Las Notas de Salida son Ralladura de limón, bergamota, menta y abrótano; las Notas de Corazón son lavanda, piña, geranio y notas verdes; las Notas de Fondo son sándalo, cedro, Amberwood, Iso E Super y haba tonka.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/chanel-bleu.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 1,
    badge: "low",
  },
  {
    id: "acqua-profondo",
    brand: "Acqua Di Gio Profondo",
    name: "Profondo",
    description:
      " Las Notas de Salida son notas marinas, Aquozone, bergamota y mandarina verde; las Notas de Corazón son romero, lavanda, ciprés y resina almáciga del lentisco; las Notas de Fondo son Notas minerales, almizcle, pachulí y ámbar.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/profondo.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 15,
  },
  {
    id: "black-opium-yves-saint-laurent",
    brand: "Yves Saint Laurent",
    name: "Black Opium",
    description:
      "Notas de salida son pera, pimienta rosa y flor de azahar del naranjo. Notas de corazón son café, jazmín y almendra amarga. Notas de fondo son vainilla, pachulí y cedro.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/black-opium.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 6,
  },
  {
    id: "ralph-lauren-ralph",
    brand: "Ralph Lauren",
    name: "Ralph Lauren Ralph",
    description:
      "Hojas de manzano,mandarina italiana,osmanto japonés. Fresia amarilla,magnolia y boronia parda. Notas de Fondo son almizcle e iris blanco.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/ralph-ralp.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 6,
  },
  {
    id: "212-sexy-carolina-herrera",
    brand: "Carolina Herrera",
    name: "212 Sexy",
    description:
      "Las Notas de Salida son pimienta rosa, mandarina y bergamota; las Notas de Corazón son algodón de azúcar, gardenia, flores, pelargonio y rosa; las Notas de Fondo son vainilla, almizcle, sándalo, caramelo, pachulí y violeta.2",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/212-sexy.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 5,
    badge: "low",
  },
  {
    id: "tommy-hilfiger-impact",
    brand: "Tommy Hilfiger",
    name: "Impact",
    description:
      "La Nota de Salida es elemí; la Nota de Corazón es madera de oud; las Notas de Fondo son gamuza y vainilla.im",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/impact.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 4,
  },
  {
    id: "valentino-born-in-roma",
    brand: "Valentino",
    name: "Born in Roma",
    description:
      "La Nota de Salida es vainilla; la Nota de Corazón es lavanda; la Nota de Fondo es vetiver.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/born-in-roma.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "one-million-paco-rabanne",
    brand: "Paco Rabanne",
    name: "One Million",
    description:
      "La fragrancia contiene nardos, notas solares, sal, aceite de Monoi, ámbar gris, cuero, cachemira, ládano y pino.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/one-million.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "armani-code-giorgio-armani",
    brand: "Giorgio Armani",
    name: "Armani Code",
    description:
      "Las Notas de Salida son bergamota y hojas del bergamoto; las Notas de Corazón son iris, aldehídos, esclarea y raíz de lirio; las Notas de Fondo son haba tonka y cedro.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/armani-code.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "bad-boy-carolina-herrera",
    brand: "Carolina Herrera",
    name: "Bad Boy",
    description:
      "Las Notas de Salida son pimienta blanca, bergamota y pimienta rosa; las Notas de Corazón son cedro y esclarea; las Notas de Fondo son haba tonka y cacao.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/bad-boy.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "bharara-king",
    brand: "Bharara",
    name: "King",
    description:
      "Las Notas de Salida son naranja, bergamota y limón (lima ácida); la Nota de Corazón es notas afrutadas; las Notas de Fondo son vainilla, almizcle blanco y ámbar.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/king.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "angel-mugler-thierry-mugler",
    brand: "Thierry Mugler",
    name: "Angel Mugler",
    description:
      "Las Notas de Salida son algodón de azúcar, coco, casis (grosellero negro), melón, jazmín, bergamota, piña y mandarina; las Notas de Corazón son miel, bayas rojas, zarzamora (frambuesa negra), ciruela, chabacano, jazmín, durazno (melocotón), nuez moscada, alcaravea, orquídea, rosa y lirio de los valles (muguete); las Notas de Fondo son pachulí, chocolate, caramelo, vainilla, haba tonka, ámbar, almizcle y sándalo. ",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/angel-mugler.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "janeiro-pink-68",
    brand: "Sol Janeiro",
    name: "Sol Janeiro Pink 68",
    description:
      'En Brasil, un secreto de belleza esencial es ser "cheirosa" (sheh-ro-zah), lo que significa oler siempre delicioso. Vibrante e inesperado, este aroma afrutado-floral ofrece una tentación transportiva a través de los abundantes jardines soleados de Río. Este aroma inmersivo se besa de alegría y siempre es acogedor.',
    price: "$6.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/sol-janeiro-pink-68.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "acqua-di-gio-tradition",
    brand: "Giorgio Armani",
    name: "Acqua Di Gio Tradition",
    description:
      "Define la masculinidad con una mezcla de notas marinas, cítricas (bergamota, limón) y un fondo amaderado suave.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/acqua-di-gio-tradition.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "le-male-jpg",
    brand: "Jean Paul Gaultier",
    name: "Le Male",
    description:
      "Una fragancia que evoca la elegancia y sofisticación del hombre moderno, con notas de salida frescas y un fondo amaderado.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/le-male.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "black-xs-paco-rabanne",
    brand: "Paco Rabanne",
    name: "Black XS",
    description:
      "Una fragancia que combina notas de frutas frescas con un fondo amaderado y especiado.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/black-xs-paco-rabanne.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "lacoste-pure",
    brand: "Lacoste",
    name: "Lacoste Pure",
    description:
      "Una fragancia fresca y energizante que combina notas cítricas con un fondo amaderado.",
    price: "$6.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/lacoste-pure.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "212-vip-carolina-herrera",
    brand: "Carolina Herrera",
    name: "212 VIP",
    description:
      "Una fragancia que captura la esencia de la vida nocturna de Nueva York, con notas de ron, maracuyá y vainilla.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/212-vip-carolina-herrera.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "212-vip-black-carolina-herrera",
    brand: "Carolina Herrera",
    name: "212 VIP Black",
    description:
      "Fragancia masculina de la familia olfativa Aromática Fougère. Lanzada en 2017 y creada por los perfumistas Carlos Benaïm y Anne Flipo, es un aroma audaz, magnético y sofisticado, ideal para la noche y climas fríos.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/212-vip-black-carolina-herrera.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "azzaro-most-wanted",
    brand: "Azzaro",
    name: "Most Wanted",
    description:
      "Fragancia intensa y adictiva que destaca por su carácter dulce y especiado con un fondo profundo y masculino",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/azzaro-most-wanted.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
  },
  {
    id: "idole-lancome",
    brand: "Lancôme",
    name: "Idole",
    description:
      "Fragancia moderna de la familia olfativa Chipre Floral. Se caracteriza por ser un aroma limpio, fresco y luminoso, diseñado para mujeres empoderadas y decididas. ",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/idole-lancome.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 15,
    badge: "new",
  },
  {
    id: "vs-velvet-petals",
    brand: "Victoria Secret",
    name: "VS Velvet Petals",
    description:
      "Aroma dulce, cálido y floral. Se destaca por su combinación de notas de glaseado de almendras y flores exuberantes, dejando una sensación cremosa, romántica y envolvente en la piel.",
    price: "$6.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/vs-velvet-petals.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 15,
    badge: "new",
  },
  {
    id: "212-rose-carolina-herrera",
    brand: "Carolina Herrera",
    name: "212 Rose",
    description:
      "Floral Frutal. Su aroma es efervescente, sofisticado y fresco, con un toque dulce y jugoso muy característico.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/212-rose-carolina-herrera.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 15,
    badge: "new",
  },
  {
    id: "moschino-toy-2-bubble-gum",
    brand: "Moschino",
    name: "Toy 2 Bubble Gum",
    description:
      "Una fragancia dulce y jugosa que combina notas de frutas frescas con un fondo amaderado.",
    price: "$15.000",
    volume: "25",
    concentration: "EDT",
    image: "/images/moschino-toy-2-bubble-gum.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 15,
    badge: "new",
  },
  {
    id: "212-mujer-nyc-carolina-herrera",
    brand: "Carolina Herrera",
    name: "212 Mujer NYC",
    description:
      "Una fragancia fresca y energizante que combina notas cítricas con un fondo amaderado.",
    price: "$15.000",
    volume: "25",
    concentration: "EDT",
    image: "/images/212-mujer-nyc-carolina-herrera.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 15,
    badge: "new",
  },
  {
    id: "yves-saint-laurent-hombre",
    brand: "Yves Saint Laurent",
    name: "Hombre",
    description:
      "Una fragancia masculina y moderna que combina notas cítricas con un fondo amaderado.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/yves-saint-laurent-hombre.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 15,
    badge: "new",
  },
  {
    id: "scandal-pour-homme-jean-paul-gaultier",
    brand: "Jean Paul Gaultier",
    name: "Scandal Pour Homme",
    description:
      "Las Notas de Salida son mandarina y esclarea; las Notas de Corazón son caramelo y haba tonka; la Nota de Fondo es vetiver.",
    price: "$15.000",
    volume: "25",
    concentration: "EDT",
    image: "/images/scandal-pour-homme-jean-paul-gaultier.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 15,
    badge: "new",
  },
  {
    id: "eros-versace",
    brand: "Versace",
    name: "Eros",
    description:
      "Combina un frescor inicial vibrante con una base cálida y cremosa, destacando por su alta concentración y duración excepcional en la piel",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/eros-versace.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 15,
    badge: "new",
  },
  {
    id: "polo-blue-ralph-lauren",
    brand: "Ralph Lauren",
    name: "Polo Blue",
    description:
      "Una fragancia fresca y energizante que combina notas cítricas con un fondo amaderado.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/polo-blue-ralph-lauren.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "cloud-pink-ag",
    brand: "Ariana Grande",
    name: "Cloud Pink",
    description:
      "Mezcla jugosas frutas y bayas con un corazón cremoso de coco y orquídea de vainilla, asentándose en una base cálida y adictiva de praliné y maderas ambarinas.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/cloud-pink-ag.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "one-million-royale-paco-rabanne",
    brand: "Paco Rabanne",
    name: "One Million Royale",
    description:
      "Se caracteriza por ser un aroma atrevido, elegante y con una gran fijación, ideal para destacar en eventos nocturnos o climas frescos.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/one-million-royal.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "invictus-victory-paco-rabanne",
    brand: "Paco Rabanne",
    name: "Invictus Victory",
    description:
      "Es una fragancia masculina intensa y seductora, lanzada en 2021, que pertenece a la familia olfativa Ámbar. Destaca por su contraste entre una frescura brillante y una base cálida y dulce, siendo ideal para las noches y las estaciones frías",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/invictus-victory.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "invictus-edt-paco-rabanne",
    brand: "Paco Rabanne",
    name: "Invictus",
    description:
      "Las Notas de Salida son notas marinas, toronja (pomelo) y mandarina; las Notas de Corazón son hoja de laurel y jazmín; las Notas de Fondo son ámbar gris, madera de gaiac, musgo de roble y pachulí.",
    price: "$15.000",
    volume: "25",
    concentration: "EDT",
    image: "/images/invictus-edt.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "azzaro-by-night",
    brand: "Azzaro",
    name: "By Night",
    description:
      "Las Notas de Salida son canela, mandarina, lavanda y limón (lima ácida); las Notas de Corazón son notas afrutadas, incienso, comino y cedro rojo; las Notas de Fondo son tabaco, vainilla, cedro, cuero, benjuí, Iso E Super, ciprés y pachulí.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/azzaro-by-night.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "armani-stronger-with-you",
    brand: "Armani",
    name: "Stronger With You",
    description:
      "Se destacan por su irresistible acorde de castaña, vainilla y un toque aromático, lo que los convierte en perfumes ideales para climas fríos o salidas nocturnas",
    price: "$15.000",
    volume: "25",
    concentration: "EDT",
    image: "/images/armani-stronger-with-you.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "armani-stronger-with-you",
    brand: "Armani",
    name: "Stronger With You",
    description:
      "Se destacan por su irresistible acorde de castaña, vainilla y un toque aromático, lo que los convierte en perfumes ideales para climas fríos o salidas nocturnas",
    price: "$15.000",
    volume: "25",
    concentration: "EDT",
    image: "/images/armani-stronger-with-you.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "invictus-platinum-paco-rabanne",
    brand: "Paco Rabanne",
    name: "Invictus Platinum",
    description:
      "Destaca por un intenso frescor mentolado que combina notas cítricas, aromáticas y un fondo amaderado. Es ideal para hombres jóvenes y dinámicos que buscan un aroma versátil para el día a día.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/invictus-platinum.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "creed-aventus",
    brand: "Creed",
    name: "Aventus",
    description:
      "Icónico perfume de nicho para hombres lanzado en 2010 por la casa Creed. Conocido por su aroma afrutado y amaderado, destaca por sus notas de piña, bergamota, abedul y almizcle.",
    price: "$20.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/creed-aventus.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "halloween-man",
    brand: "Halloween",
    name: "Man",
    description:
      "Es una fragancia oriental amaderada para hombres lanzada en 2012. Destaca por su aroma dulce, fresco y especiado, ideal para climas fríos y uso nocturno.",
    price: "$15.000",
    volume: "25",
    concentration: "EDT",
    image: "/images/halloween-man.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "sweet-tooth-caramel",
    brand: "Sweet Tooth",
    name: "Caramel",
    description:
      "Sofisticada fragancia ámbar avainillada lanzada en 2023. Evoluciona desde un inicio cítrico-almendrado hacia un corazón de chocolate oscuro, asentándose en una base cálida y cremosa de caramelo, sándalo y pachulí.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/sweet-caramel.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "good-girl-carlina-herrera",
    brand: "Carlina Herrera",
    name: "Good Girl",
    description:
      "Fragancia oriental floral que celebra la dualidad de la mujer moderna: elegante y sofisticada, pero también audaz, sensual y misteriosa. Es famoso por su icónico frasco con forma de tacón de aguja y su aroma dulce y duradero.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/good-girl.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "nuit-tresor-lancome",
    brand: "Lancôme",
    name: "La Nuit Tresor",
    description:
      "Concebida como una poción de amor moderna, destaca por ser intensa, dulce, misteriosa y con un toque floral.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/nuit-tresor.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "coco-chanel-mademoiselle",
    brand: "Chanel",
    name: "Coco Mademoiselle",
    description:
      "Perfume floral oriental vibrante y sofisticado. Creado en 2001 por Jacques Polge, captura el espíritu rebelde y audaz de la joven modista. Destaca por su aroma de naranja viva, su corazón de rosa y jazmín, y un fondo duradero de pachulí y vainilla.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/coco-made.png",
    categories: ["mujer"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "acqua-di-gio-parfum",
    brand: "Armani",
    name: "Acqua di Gio Parfum",
    description:
      "De la familia Amaderada Acuática, lanzada en 2023 y creada por el maestro perfumista Alberto Morillas. Combina la icónica frescura marina de la línea con un fondo oscuro, ahumado y sofisticado.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/aqua-di-gio-parfum.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
  {
    id: "polo-sport-ralph-lauren",
    brand: "Ralph Lauren",
    name: "Polo Sport",
    description:
      "Es un clásico atemporal de la perfumería masculina, famoso por su energía y frescura. Lanzado en 1994 y creado por Harry Fremont, pertenece a la familia olfativa Aromática Verde. Es la fragancia perfecta para el hombre activo, ideal para el uso diario o el gimnasio gracias a sus vibrantes notas.",
    price: "$15.000",
    volume: "25",
    concentration: "EDP",
    image: "/images/polo-sport.png",
    categories: ["hombre"],
    stockStatus: "in-stock",
    stockCount: 11,
    badge: "new",
  },
];

const stockCount = PRODUCTS.reduce(
  (total, product) => total + product.stockCount,
  0,
);

export const STATS: Stat[] = [
  { value: `${PRODUCTS.length}`, label: "Fragancias" },
  /* { value: "14", label: "Marcas" }, */
  { value: `${stockCount}`, label: "En stock hoy" },
  { value: "24h", label: "Despacho" },
];
